[package]
name = "cphd_rs"
version = "0.1.0"
edition = "2024"
description = "NITF CPHD I/O tools" 
license = "MIT OR Apache-2.0" 
repository = "https://https://github.com/shauglandarka/cphd-rs"
readme = "README.md"  
keywords = ["Radar", "SAR", "NITF", "CPHD"] 
categories = ["science", "algorithms"]    

[dependencies]
byteorder = "1.5.0"
memmap2 = "0.9.11"
ndarray = "0.17.2"
num-complex = "0.4.6"
quick-xml = { version = "0.41.0", features = ["serialize"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"

[dev-dependencies]
fmt = "0.1.0"

[profile.dev]
opt-level = 0
debug = true
